#Location for the zipped files
zip: /Users/looseymoose/Desktop/testing/polyjuice_testing/zipped_folders

#This dictionary has a dictionary of tags whose value should be modified
modifications:
  #InstanceCreatorUID: 
  SOPInstanceUID: ''
  AccessionNumber: ''
  InstitutionName: ''
  #InstitutionAddress: 
  ReferringPhysicianName: ''
  #ReferringPhysicianAddress: 
  #ReferringPhysicianTelephoneNumbers: 
  StationName: ''
  StudyDescription: ''
  SeriesDescription: ''
  #InstitutionalDepartmentName: 
  #PhysicianOfRecord: 
  #PerformingPhysicianName:
  #NameOfPhysicianReadingStudy: 
  #OperatorName: 
  #AdmittingDiadnosesDescription: 
  #ReferencedSOPInstanceUID: 
  #DerivationDescription: 
  PatientName: Anonymous
  #PatientID: ??
  PatientBirthDate: "19990909"
  #PatientBirthTime: 
  PatientSex: ''
  #OtherPatientIDs:
  #OtherPatientNames:
  PatientAge: ''
  #PatientSize:
  PatientWeight: ''
  #MedicalRecordLocator:
  EthnicGroup: ''
  #Occupation:
  #AdditionalPatientHistory:
  #PatientComments:
  #DeviceSerialNumber:
  ProtocolName: ''
  StudyInstanceUID: ''
  SeriesInstanceUID: ''
  StudyID: ''
  #FrameOfReferenceUID:
  #SynchronizationonFrameOfReferenceUID:
  #ImageComments:
  #RequestAttributesSequence:
  #UID:
  #ContentSequence:
  #StorageMediaFileSetUID:
  #ReferencedFrameOfReferenceUID:
  #RelatedFrameOfReferenceUID:
  RescaleIntercept: Null
  RescaleSlope: Null
  RescaleType: Null

new_patient_ids:
  - old: '110004'
    new: '9999999'
  - old: wklfdsdfkm
    new: dfsljf

#Optional: Use the dictionaries below to go through multiple ISOs

#This is the filepath for the input and output. Put the actual files in the IO_pairs dictionary.
in_data_root: /Users/amineni95/Desktop
out_data_root: /Users/amineni95/Desktop

io_pairs:
  - input: 110004_6-3-2009.iso
    output: clean_test
  - input: 110024-5-2-2013-PET-Amyvid-Florbetapir.iso
    output: clean_test

ignore:
  - .DS_Store
